import { GetServerSidePropsContext, type NextPage } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";

type Props = {
  session: {
    user: {
      name: string;
      email: string;
      image: string;
      balance: number;
      id: string;
      emailVerified: string | null;
    };
  };
};

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/auth/signin",
      },
    };
  }
  return {
    props: session,
  };
};

const Dice: NextPage<Props> = (props) => {
  console.log(props);
  return (
    <>
      <Head>
        <title>Roulettor.com</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center"></div>
    </>
  );
};

export default Dice;
