import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

import Roulette from "~/components/Roulette";

const RoulettePage: NextPage = () => {
  const { data: session } = useSession();
  const router = useRouter();

  if (!session) {
    router.push("/auth/signin");
    return null;
  }

  return (
    <>
      <Head>
        <title>Roulettor</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative mx-auto flex min-h-screen max-w-6xl flex-col items-center">
        <Roulette />
      </main>
    </>
  );
};

export default RoulettePage;
