import { User } from "@prisma/client";
import axios from "axios";
import type { GetServerSidePropsContext, NextPage } from "next";
import { Session } from "next-auth";
import { getSession } from "next-auth/react";
import Head from "next/head";
import BetStation from "~/components/BetStation";

import RoulettePanel from "~/components/RoulettePanel";
import RouletteSpinner from "~/components/RouletteSpinner";
import RouletteStatusBar from "~/components/RouletteStatusBar";
import { env } from "~/env.mjs";

type Props = {
  session: Session;
  balance: number;
};

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/auth/signin",
      },
    };
  }

  const res: {
    data: {
      user: User;
    };
  } = await axios.get(`${env.NEXTAUTH_URL}/api/user/${session.user.id}`);

  return {
    props: { session, balance: res.data.user.balance },
  };
};

const RoulettePage: NextPage<Props> = ({ session, balance }) => {
  return (
    <>
      <Head>
        <title>Roulettor</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative mx-auto flex min-h-screen max-w-6xl flex-col gap-4">
        <RouletteSpinner />
        <RouletteStatusBar totalTimeInSeconds={60} />
        {/* <RoulettePanel /> */}
        <BetStation balance={balance} game="roulette" />
      </main>
    </>
  );
};

export default RoulettePage;
