import type { NextPage } from "next";
import Head from "next/head";

import Roulette from "~/components/Roulette";

const RoulettePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Roulettor</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative mx-auto flex min-h-screen max-w-6xl flex-col items-center">
        <Roulette />
      </main>
    </>
  );
};

export default RoulettePage;
