import "./globals.css";
import type { Metadata } from "next";
import NextAuthProvider from "@/components/NextAuthProviderr";
import Navbar from "@/components/Navbar";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={poppins.className}>
          <div className="max-w-screen-xl mx-auto relative w-full text-text">
            <Navbar />
            {children}
          </div>
        </body>
      </NextAuthProvider>
    </html>
  );
}
