import "./globals.css";
import type { Metadata } from "next";
import NextAuthProvider from "@/components/NextAuthProviderr";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={inter.className}>
          <div className="mx-auto max-w-6xl">
            <Navbar />
            {children}
            <Toaster />
          </div>
        </body>
      </NextAuthProvider>
    </html>
  );
}
